-- Define your visual elements here
-- For examples, and a complete list on the possible elements and their 
-- properties, go to https://github.com/cmanon/conky-draw/
-- (and be sure to use the lastest version)

-- Blue / Green
color0 = 0x4dffff
color1 = 0x2d6862
color2 = 0x0d2a32
color3 = 0x49b045
color4 = 0xffffff
color5 = 0x000000
color6 = 0xff5140

-- Red
-- color0 = 0xff4e24
-- color1 = 0x2d6862
-- color2 = 0x320200
-- color3 = 0xffa73e
-- color4 = 0x888888
-- color5 = 0x080401
-- color6 = 0xff5140

cpu_detailed_start_x = 210
cpu_detailed_start_y = 74
cpu_detailed_end_x = 340
cpu_detailed_increment = 8

graph_stroke_color_alpha = 1.0
graph_background_color_alpha = 0.2

single_value_rectangle_height = 30

elements = {
    {
        kind = 'rectangle',
        from = {x = 20, y = 10},
        width = 360,
        height = 790,
        stroke_color = color0,
        stroke_color_alpha = 1.0,
        stroke_width = 3,
        fill_color = color5,
        fill_color_alpha = 0.5,
    },
    {
        kind = 'rectangle',
        from = {x = 20, y = 10},
        width = 360,
        height = 40,
        stroke_color = color0,
        stroke_color_alpha = 1.0,
        stroke_width = 3,
        fill_color = color2,
        fill_color_alpha = 0.8,
    },
    {
        kind = 'rectangle',
        from = {x = 20, y = 50},
        width = 180,
        height = 100,
        stroke_color = color0,
        stroke_color_alpha = 1.0,
        stroke_width = 3,
        fill_color = color2,
        fill_color_alpha = 0,
    },
    {
        kind = 'rectangle',
        from = {x = 200, y = 50},
        width = 180,
        height = 100,
        stroke_color = color0,
        stroke_color_alpha = 1.0,
        stroke_width = 3,
        fill_color = color2,
        fill_color_alpha = 0,
    },
    {
        kind = 'rectangle',
        from = {x = 20, y = 150},
        width = 180,
        height = single_value_rectangle_height,
        stroke_color = color0,
        stroke_color_alpha = 1.0,
        stroke_width = 3,
        fill_color = color2,
        fill_color_alpha = 0,
    },
    {
        kind = 'rectangle',
        from = {x = 200, y = 150},
        width = 180,
        height = single_value_rectangle_height,
        stroke_color = color0,
        stroke_color_alpha = 1.0,
        stroke_width = 3,
        fill_color = color2,
        fill_color_alpha = 0,
    },
    {
        kind = 'rectangle',
        from = {x = 20, y = 180},
        width = 180,
        height = single_value_rectangle_height,
        stroke_color = color0,
        stroke_color_alpha = 1.0,
        stroke_width = 3,
        fill_color = color2,
        fill_color_alpha = 0,
    },
    {
        kind = 'rectangle',
        from = {x = 200, y = 180},
        width = 180,
        height = single_value_rectangle_height,
        stroke_color = color0,
        stroke_color_alpha = 1.0,
        stroke_width = 3,
        fill_color = color2,
        fill_color_alpha = 0,
    },
    -- {
    --     kind = 'bar_graph',
    --     conky_value = 'cpu cpu0',
    --     from = {x = 40, y = 40},
    --     to = {x = 360, y = 40},
    --     bar_color = color0,
    --     bar_alpha = 0.8,
    --     bar_thickness = 20,
    --     background_color = color1,
    --     background_alpha = 0.6,
    --     background_thickness = 20,
    --     graduated = true,
    --     number_graduation = 20,
    --     space_between_graduation = 1.5,
    -- },
    -- CPU
    {
        kind = 'ring_graph',
        conky_value = 'cpu cpu0',
        center = {x = 110, y = 130},
        radius = 50,
        bar_color = color0,
        bar_thickness = 12,
        background_color = color4,
        background_alpha = graph_background_color_alpha,
        background_thickness = 6,
        start_angle = 180,
        end_angle = 360,
    },
    {
        kind = 'bar_graph',
        conky_value = 'cpu cpu1',
        from = {x = cpu_detailed_start_x, y = cpu_detailed_start_y},
        to = {x = cpu_detailed_end_x, y = cpu_detailed_start_y},
        bar_color = color0,
        bar_alpha = 0.8,
        bar_thickness = 4,
        background_color = color4,
        background_alpha = graph_background_color_alpha,
        background_thickness = 2,
    },
    {
        kind = 'bar_graph',
        conky_value = 'cpu cpu2',
        from = {x = cpu_detailed_start_x, y = cpu_detailed_start_y + (cpu_detailed_increment * 1)},
        to = {x = cpu_detailed_end_x, y = cpu_detailed_start_y + (cpu_detailed_increment * 1)},
        bar_color = color0,
        bar_alpha = 0.8,
        bar_thickness = 4,
        background_color = color4,
        background_alpha = graph_background_color_alpha,
        background_thickness = 2,
    },
    {
        kind = 'bar_graph',
        conky_value = 'cpu cpu3',
        from = {x = cpu_detailed_start_x, y = cpu_detailed_start_y + (cpu_detailed_increment * 2)},
        to = {x = cpu_detailed_end_x, y = cpu_detailed_start_y + (cpu_detailed_increment * 2)},
        bar_color = color0,
        bar_alpha = 0.8,
        bar_thickness = 4,
        background_color = color4,
        background_alpha = graph_background_color_alpha,
        background_thickness = 2,
    },
    {
        kind = 'bar_graph',
        conky_value = 'cpu cpu4',
        from = {x = cpu_detailed_start_x, y = cpu_detailed_start_y + (cpu_detailed_increment * 3)},
        to = {x = cpu_detailed_end_x, y = cpu_detailed_start_y + (cpu_detailed_increment * 3)},
        bar_color = color0,
        bar_alpha = 0.8,
        bar_thickness = 4,
        background_color = color4,
        background_alpha = graph_background_color_alpha,
        background_thickness = 2,
    },
    {
        kind = 'bar_graph',
        conky_value = 'cpu cpu5',
        from = {x = cpu_detailed_start_x, y = cpu_detailed_start_y + (cpu_detailed_increment * 4)},
        to = {x = cpu_detailed_end_x, y = cpu_detailed_start_y + (cpu_detailed_increment * 4)},
        bar_color = color0,
        bar_alpha = 0.8,
        bar_thickness = 4,
        background_color = color4,
        background_alpha = graph_background_color_alpha,
        background_thickness = 2,
    },
    {
        kind = 'bar_graph',
        conky_value = 'cpu cpu6',
        from = {x = cpu_detailed_start_x, y = cpu_detailed_start_y + (cpu_detailed_increment * 5)},
        to = {x = cpu_detailed_end_x, y = cpu_detailed_start_y + (cpu_detailed_increment * 5)},
        bar_color = color0,
        bar_alpha = 0.8,
        bar_thickness = 4,
        background_color = color4,
        background_alpha = graph_background_color_alpha,
        background_thickness = 2,
    },
    {
        kind = 'bar_graph',
        conky_value = 'cpu cpu7',
        from = {x = cpu_detailed_start_x, y = cpu_detailed_start_y + (cpu_detailed_increment * 6)},
        to = {x = cpu_detailed_end_x, y = cpu_detailed_start_y + (cpu_detailed_increment * 6)},
        bar_color = color0,
        bar_alpha = 0.8,
        bar_thickness = 4,
        background_color = color4,
        background_alpha = graph_background_color_alpha,
        background_thickness = 2,
    },
    {
        kind = 'bar_graph',
        conky_value = 'cpu cpu8',
        from = {x = cpu_detailed_start_x, y = cpu_detailed_start_y + (cpu_detailed_increment * 7)},
        to = {x = cpu_detailed_end_x, y = cpu_detailed_start_y + (cpu_detailed_increment * 7)},
        bar_color = color0,
        bar_alpha = 0.8,
        bar_thickness = 4,
        background_color = color4,
        background_alpha = graph_background_color_alpha,
        background_thickness = 2,
    },
    {
        kind = 'bar_graph',
        conky_value = 'cpu cpu9',
        from = {x = cpu_detailed_start_x, y = cpu_detailed_start_y + (cpu_detailed_increment * 8)},
        to = {x = cpu_detailed_end_x, y = cpu_detailed_start_y + (cpu_detailed_increment * 8)},
        bar_color = color0,
        bar_alpha = 0.8,
        bar_thickness = 4,
        background_color = color4,
        background_alpha = graph_background_color_alpha,
        background_thickness = 2,
    },
    -- Memory
    {
        kind = 'rectangle',
        from = {x = 20, y = 210},
        width = 360,
        height = 40,
        stroke_color = color0,
        stroke_color_alpha = 1.0,
        stroke_width = 3,
        fill_color = color2,
        fill_color_alpha = 0.8,
    },
    {
        kind = 'rectangle',
        from = {x = 20, y = 250},
        width = 360,
        height = 70,
        stroke_color = color0,
        stroke_color_alpha = 1.0,
        stroke_width = 3,
        fill_color = color2,
        fill_color_alpha = 0,
    },
    {
        kind = 'bar_graph',
        conky_value = 'memperc',
        from = {x = 30, y = 285},
        to = {x = 370, y = 285},
        bar_color = color0,
        bar_alpha = 0.8,
        bar_thickness = 20,
        background_color = color4,
        background_alpha = graph_background_color_alpha,
        background_thickness = 20,
        graduated = true,
        number_graduation = 20,
        space_between_graduation = 1.2,
    },
    -- File System
    {
        kind = 'rectangle',
        from = {x = 20, y = 320},
        width = 360,
        height = 40,
        stroke_color = color0,
        stroke_color_alpha = 1.0,
        stroke_width = 3,
        fill_color = color2,
        fill_color_alpha = 0.8,
    },
    {
        kind = 'rectangle',
        from = {x = 20, y = 360},
        width = 360,
        height = 70,
        stroke_color = color0,
        stroke_color_alpha = 1.0,
        stroke_width = 3,
        fill_color = color2,
        fill_color_alpha = 0,
    },
    {
        kind = 'rectangle',
        from = {x = 20, y = 430},
        width = 180,
        height = single_value_rectangle_height,
        stroke_color = color0,
        stroke_color_alpha = 1.0,
        stroke_width = 3,
        fill_color = color2,
        fill_color_alpha = 0,
    },
    {
        kind = 'rectangle',
        from = {x = 200, y = 430},
        width = 180,
        height = single_value_rectangle_height,
        stroke_color = color0,
        stroke_color_alpha = 1.0,
        stroke_width = 3,
        fill_color = color2,
        fill_color_alpha = 0,
    },
    {
        kind = 'rectangle',
        from = {x = 20, y = 460},
        width = 180,
        height = single_value_rectangle_height,
        stroke_color = color0,
        stroke_color_alpha = 1.0,
        stroke_width = 3,
        fill_color = color2,
        fill_color_alpha = 0,
    },
    {
        kind = 'rectangle',
        from = {x = 200, y = 460},
        width = 180,
        height = single_value_rectangle_height,
        stroke_color = color0,
        stroke_color_alpha = 1.0,
        stroke_width = 3,
        fill_color = color2,
        fill_color_alpha = 0,
    },
    {
        kind = 'bar_graph',
        conky_value = 'fs_used_perc /',
        from = {x = 30, y = 395},
        to = {x = 370, y = 395},
        bar_color = color0,
        bar_alpha = 0.8,
        bar_thickness = 20,
        background_color = color4,
        background_alpha = graph_background_color_alpha,
        background_thickness = 20,
        graduated = true,
        number_graduation = 20,
        space_between_graduation = 1.2,
    },
    -- Network
    {
        kind = 'rectangle',
        from = {x = 20, y = 490},
        width = 360,
        height = 40,
        stroke_color = color0,
        stroke_color_alpha = 1.0,
        stroke_width = 3,
        fill_color = color2,
        fill_color_alpha = 0.8,
    },
    {
        kind = 'rectangle',
        from = {x = 20, y = 530},
        width = 360,
        height = 70,
        stroke_color = color0,
        stroke_color_alpha = 1.0,
        stroke_width = 3,
        fill_color = color2,
        fill_color_alpha = 0,
    },
    {
        kind = 'rectangle',
        from = {x = 20, y = 600},
        width = 180,
        height = single_value_rectangle_height,
        stroke_color = color0,
        stroke_color_alpha = 1.0,
        stroke_width = 3,
        fill_color = color2,
        fill_color_alpha = 0,
    },
    {
        kind = 'rectangle',
        from = {x = 200, y = 600},
        width = 180,
        height = single_value_rectangle_height,
        stroke_color = color0,
        stroke_color_alpha = 1.0,
        stroke_width = 3,
        fill_color = color2,
        fill_color_alpha = 0,
    },
    {
        kind = 'rectangle',
        from = {x = 20, y = 630},
        width = 180,
        height = single_value_rectangle_height,
        stroke_color = color0,
        stroke_color_alpha = 1.0,
        stroke_width = 3,
        fill_color = color2,
        fill_color_alpha = 0,
    },
    {
        kind = 'rectangle',
        from = {x = 200, y = 630},
        width = 180,
        height = single_value_rectangle_height,
        stroke_color = color0,
        stroke_color_alpha = 1.0,
        stroke_width = 3,
        fill_color = color2,
        fill_color_alpha = 0,
    },
    {
        kind = 'bar_graph',
        conky_value = 'wireless_link_qual_perc wlan0',
        from = {x = 30, y = 565},
        to = {x = 370, y = 565},
        bar_color = color0,
        bar_alpha = 0.8,
        bar_thickness = 20,
        background_color = color4,
        background_alpha = graph_background_color_alpha,
        background_thickness = 20,
        graduated = false,
        number_graduation = 20,
        space_between_graduation = 1.2,
        change_color_on_critical = false,
    },
    -- NVIDIA
    {
        kind = 'rectangle',
        from = {x = 20, y = 660},
        width = 360,
        height = 40,
        stroke_color = color0,
        stroke_color_alpha = 1.0,
        stroke_width = 3,
        fill_color = color2,
        fill_color_alpha = 0.8,
    },
    {
        kind = 'rectangle',
        from = {x = 20, y = 700},
        width = 180,
        height = single_value_rectangle_height,
        stroke_color = color0,
        stroke_color_alpha = 1.0,
        stroke_width = 3,
        fill_color = color2,
        fill_color_alpha = 0,
    },
    {
        kind = 'rectangle',
        from = {x = 200, y = 700},
        width = 180,
        height = single_value_rectangle_height,
        stroke_color = color0,
        stroke_color_alpha = 1.0,
        stroke_width = 3,
        fill_color = color2,
        fill_color_alpha = 0,
    },
    {
        kind = 'rectangle',
        from = {x = 20, y = 730},
        width = 180,
        height = single_value_rectangle_height,
        stroke_color = color0,
        stroke_color_alpha = 1.0,
        stroke_width = 3,
        fill_color = color2,
        fill_color_alpha = 0,
    },
    {
        kind = 'rectangle',
        from = {x = 200, y = 730},
        width = 180,
        height = single_value_rectangle_height,
        stroke_color = color0,
        stroke_color_alpha = 1.0,
        stroke_width = 3,
        fill_color = color2,
        fill_color_alpha = 0,
    },
    -- Misc
    {
        kind = 'rectangle',
        from = {x = 20, y = 760},
        width = 360,
        height = 40,
        stroke_color = color0,
        stroke_color_alpha = 1.0,
        stroke_width = 3,
        fill_color = color2,
        fill_color_alpha = 0.8,
    },
}
