general.import = [
    "~/.config/alacritty/themes/dracula.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"

opacity = 1.0
blur = true

option_as_alt = "Both"

[font]
normal.family = "JetBrainsMono Nerd Font"
size = 14

[cursor]
style.shape = "Block"
style.blinking = "On"
